[package]
name = "wasm_pack_world"
version = "0.1.0"
authors = ["Sendil Kumar"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
